import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "@/components/ui/sonner";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";

// Limit subset to latin to reduce the font bundle size.
const inter = Inter({
  subsets: ["latin"],
});

/** Page-level metadata applied to the entire application by default. */
export const metadata: Metadata = {
  title: "Hrishi Docs",
  description: "Generated by create next app",
};

/**
 * Root layout shared by every route in the app. [explainMore]
 * NuqsAdapter syncs URL search params with React state. 
 * ConvexClientProvider handles auth and real-time DB connectivity.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <NuqsAdapter>
          <ConvexClientProvider>
            <Toaster />
            {children}
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
